### ISSUE TITLE
退出登录报错

### ISSUE THREAD

**Issue by myixyt** [shopwwi/webman-auth#5]
Auth::logout();
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/20921986/203200534-62640633-d7f9-4805-ba38-4333cf51805e.png">

**Comment by myixyt** [comment]
看了一下源码，删除redis token时候使用hdel，传递的参数是数组，应该是传递多个字符串吧
<img width="757" alt="image" src="https://user-images.githubusercontent.com/20921986/203211282-0aaea51c-0a47-459e-b7b2-d4aab261a4f9.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/20921986/203211320-8ba8efde-83b5-47e7-9479-9b6df3e92033.png">

**Comment by phcent** [comment]
感谢反馈  已修正
