### ISSUE TITLE
可以不使用session来存储token吗？

### ISSUE THREAD

**Issue by winson-young** [shopwwi/webman-auth#9]
我看了源码发现accesstoken会被存储在session里，在没有传token的情况下会去session里面拿，但是我希望不用session（只要没有传token就当做空来处理），实际上虽然webman默认需要使用session，但是对于api来说基本上是无状态的，没有用到session的地方，所以想询问一下作者能否去掉这个功能。

**Comment by phcent** [comment]
这个是为了兼容不分离项目 只要是分离项目session不会生效的 除非你把cookie返回了

**Comment by winson-young** [comment]
感谢回复，原来如此，我这边已经通过其他办法来规避这个问题了，虽然个人还是希望能用配置的方式来兼容这个问题，不过作者的做法确实也无可厚非，再次谢谢作者的付出，感谢~
